version: 0.2

env:
  secrets-manager:
    TF_VAR_github_token: arn:aws:secretsmanager:us-east-1:482352589093:secret:scp-github-access-token-wl0bYW:TF_VAR_github_token
    TF_VAR_repo_owner: arn:aws:secretsmanager:us-east-1:482352589093:secret:terraform-global-variables-tw1F9n:TF_VAR_repo_owner
    TF_VAR_repo: arn:aws:secretsmanager:us-east-1:482352589093:secret:terraform-global-variables-tw1F9n:TF_VAR_repo
    TF_VAR_branch: arn:aws:secretsmanager:us-east-1:482352589093:secret:terraform-global-variables-tw1F9n:TF_VAR_branch
    TF_VAR_poll_for_changes: arn:aws:secretsmanager:us-east-1:482352589093:secret:terraform-global-variables-tw1F9n:TF_VAR_poll_for_changes

phases:
  install:
    commands:
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.1.9/terraform_1.1.9_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform

  build:
    commands:
      - cd ./tf/global
      - terraform init
      - terraform apply -auto-approve