version: 0.2

env:
  secrets-manager:
    TF_VAR_github_token: arn:aws:secretsmanager:us-east-1:482352589093:secret:scp-github-access-token-wl0bYW:TF_VAR_github_token
    TF_VAR_repo_owner: arn:aws:secretsmanager:us-east-1:482352589093:secret:scp-github-access-token-wl0bYW:repo-owner	
    TF_VAR_repo: arn:aws:secretsmanager:us-east-1:482352589093:secret:gcp-provider-config-22z8EI:repo
    TF_VAR_branch: arn:aws:secretsmanager:us-east-1:482352589093:secret:gcp-provider-config-22z8EI:branch
    TF_VAR_poll_for_changes: arn:aws:secretsmanager:us-east-1:482352589093:secret:gcp-provider-config-22z8EI:pull-for-changes

phases:
  install:
    commands:
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.1.9/terraform_1.1.9_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform

  pre_build:
    commands:
      - aws s3 cp s3://crypto-sound-terraform/credentials/gcp_creds.json .
      - export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp_creds.json

  build:
    commands:
      - cd ./tf/global
      - terraform init
      - terraform apply -auto-approve