version: 0.2

env:
  secrets-manager:
    GOOGLE_APPLICATION_CREDENTIALS: https://crypto-sound-terraform.s3.amazonaws.com/credentials/cryptosound-349002-3c657660c8e2.json
    TF_VAR_github_token: arn:aws:secretsmanager:us-east-1:482352589093:secret:scp-github-access-token-wl0bYW:TF_VAR_github_token
    TF_VAR_gcp_project: arn:aws:secretsmanager:us-east-1:482352589093:secret:gcp-provider-config-22z8EI:gcp-provider-config-project
    TF_VAR_gcp_region: arn:aws:secretsmanager:us-east-1:482352589093:secret:gcp-provider-config-22z8EI:gcp-provider-config-region
    TF_VAR_gcp_zone: arn:aws:secretsmanager:us-east-1:482352589093:secret:gcp-provider-config-22z8EI:gcp-provider-config-zone

phases:
  install:
    commands:
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.1.9/terraform_1.1.9_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform

  build:
    commands:
      - cd ./tf/global
      - terraform init
      - terraform apply -auto-approve