version: 0.2

env:
  secrets-manager:
    TF_VAR_github_token: arn:aws:secretsmanager:us-east-1:482352589093:secret:scp-github-access-token-wl0bYW:TF_VAR_github_token

phases:
  build:
    commands:
      - export DOCKER_PUSH_URL=$ECR_URL:$COMMITID
      - export ECR_URI=${ECR_URL%/*}
      - cd ./src/CryptoSoundUI
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_URI
      - docker build . -t cs-ui
      - docker tag cs-ui $DOCKER_PUSH_URL
      - docker push $DOCKER_PUSH_URL