version: 0.2

env:
  secrets-manager:
    TF_VAR_github_token: arn:aws:secretsmanager:us-east-1:482352589093:secret:scp-github-access-token-wl0bYW:TF_VAR_github_token

phases:
  build:
    commands:
      - export DOCKER_IMG_NAME=scp-cs-$ENV
      - export DOCKER_PUSH_URL=$ECR_URL/$DOCKER_IMG_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $DOCKER_PUSH_URL
      - cd ./src/CryptoSoundUI
      - docker login -u storycollector -p $DOCKER_KEY
      - docker build . -t $DOCKER_IMG_NAME
      - docker tag $DOCKER_IMG_NAME $DOCKER_PUSH_URL
      - docker image push $DOCKER_PUSH_URL