version: 0.2

env:
  secrets-manager:
    TF_VAR_github_token: arn:aws:secretsmanager:us-east-1:482352589093:secret:scp-github-access-token-wl0bYW:TF_VAR_github_token

phases:
  build:
    commands:
      - export DOCKER_IMG_NAME=cs-ui-$ENV
      - export DOCKER_PUSH_URL=$ECR_URL/$DOCKER_IMG_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - export ECR_URI=${ECR_URL%/*}
      - echo $DOCKER_PUSH_URL
      - cd ./src/CryptoSoundUI
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_URI
      - docker build . -t $DOCKER_IMG_NAME
      - docker tag $DOCKER_IMG_NAME $DOCKER_PUSH_URL
      - docker push $DOCKER_PUSH_URL