version: 0.2

env:
  secrets-manager:
    TF_VAR_github_token: arn:aws:secretsmanager:us-east-1:482352589093:secret:scp-github-access-token-wl0bYW:TF_VAR_github_token
    NUXT_ENV_CONTENTFUL_TOKEN: arn:aws:secretsmanager:us-east-1:482352589093:secret:qa-cs-config-bNTQ2q:NUXT_ENV_CONTENTFUL_TOKEN
    NUXT_ENV_ENVIRONMENT: arn:aws:secretsmanager:us-east-1:482352589093:secret:qa-cs-config-bNTQ2q:NUXT_ENV_ENVIRONMENT
    NUXT_ENV_CONTENTFUL_SPACE: arn:aws:secretsmanager:us-east-1:482352589093:secret:qa-cs-config-bNTQ2q:NUXT_ENV_CONTENTFUL_SPACE
    NUXT_ENV_CONTENTFUL_ENV: arn:aws:secretsmanager:us-east-1:482352589093:secret:qa-cs-config-bNTQ2q:NUXT_ENV_CONTENTFUL_ENV
    NUXT_ENV_FIREBASE_API_KEY: arn:aws:secretsmanager:us-east-1:482352589093:secret:qa-cs-config-bNTQ2q:NUXT_ENV_FIREBASE_API_KEY
    NUXT_ENV_FIREBASE_AUTH_DOMAIN: arn:aws:secretsmanager:us-east-1:482352589093:secret:qa-cs-config-bNTQ2q:NUXT_ENV_FIREBASE_AUTH_DOMAIN
    NUXT_ENV_FIREBASE_PROJECT_ID: arn:aws:secretsmanager:us-east-1:482352589093:secret:qa-cs-config-bNTQ2q:NUXT_ENV_FIREBASE_PROJECT_ID
    NUXT_ENV_FIREBASE_STORAGE_BUCKET: arn:aws:secretsmanager:us-east-1:482352589093:secret:qa-cs-config-bNTQ2q:NUXT_ENV_FIREBASE_STORAGE_BUCKET
    NUXT_ENV_FIREBASE_MESSAGING_SENDER_ID: arn:aws:secretsmanager:us-east-1:482352589093:secret:qa-cs-config-bNTQ2q:NUXT_ENV_FIREBASE_MESSAGING_SENDER_ID
    NUXT_ENV_FIREBASE_APP_ID: arn:aws:secretsmanager:us-east-1:482352589093:secret:qa-cs-config-bNTQ2q:NUXT_ENV_FIREBASE_APP_ID
    NUXT_ENV_FIREBASE_MEASUREMENT_ID: arn:aws:secretsmanager:us-east-1:482352589093:secret:qa-cs-config-bNTQ2q:NUXT_ENV_FIREBASE_MEASUREMENT_ID

phases:
  build:
    commands:
      - export DOCKER_PUSH_URL=$ECR_URL:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - export ECR_URI=${ECR_URL%/*}
      - cd ./src/CryptoSoundAPI
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_URI
      - docker build --build-arg PORT=$PORT . -t cs-api
      - docker tag cs-api $DOCKER_PUSH_URL
      - docker push $DOCKER_PUSH_URL
      - cd ../../src/CryptoSoundUI
      - npm install
      - npm run generate

artifacts:
  files:
    - '**/*'