version: 0.2

phases:
  install:
    commands:
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.1.9/terraform_1.1.9_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform
      
  build:
    commands:
      - cd ./tf/global
      - terraform init 
      - terraform apply -var="AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" -var="AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" -var="TF_VAR_github_token=${TF_VAR_github_token}"