version: 0.2

env:
  secrets-manager:
    TF_VAR_github_token: arn:aws:secretsmanager:us-east-1:482352589093:secret:scp-github-access-token-wl0bYW:TF_VAR_github_token

phases:
  install:
    commands:
      - curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-383.0.1-linux-x86_64.tar.gz
      - tar -xf google-cloud-cli-383.0.1-linux-x86.tar.gz
      - yes Y | ./google-cloud-sdk/install.sh
      - ./google-cloud-sdk/bin/gcloud init

  pre_build:
    commands:
      - aws s3 cp s3://crypto-sound-terraform/credentials/gcp_creds.json .
      - gcloud auth 863979559433-compute@developer.gserviceaccount.com ACCOUNT --key-file=./gcp_creds.json
      - export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp_creds.json

  build:
    commands:
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker --version
      - cd ./src/CryptoSoundUI
      - docker build . -t scp-cs-ui:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $GCP_REPO/scp-cs-ui:$CODEBUILD_RESOLVED_SOURCE_VERSION