version: 0.2

env:
  secrets-manager:
    TF_VAR_github_token: arn:aws:secretsmanager:us-east-1:482352589093:secret:scp-github-access-token-wl0bYW:TF_VAR_github_token
    CLOUDFLARE_API_TOKEN: arn:aws:secretsmanager:us-east-1:482352589093:secret:terraform-global-variables-tw1F9n:CLOUDFLARE_API_TOKEN
    TF_VAR_cloudflare_email: arn:aws:secretsmanager:us-east-1:482352589093:secret:terraform-global-variables-tw1F9n:TF_VAR_cloudflare_email

phases:
  install:
    commands:
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.1.9/terraform_1.1.9_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform

  build:
    commands:
      - export CURRENT_API_IMAGE=$(aws ecr describe-images --repository-name cs-api-container-repo-$ENV --query 'sort_by(imageDetails, &imagePushedAt)[-1]')
      - cd tf/aws
      - terraform init
      - TF_VAR_env=$ENV TF_VAR_ecr_api_repo_url=$ECR_URL TF_VAR_current_api_image_tag=CURRENT_API_IMAGE terraform apply -auto-approve